get:
  path: '/breeds'
  controller: App\Controller\Api\Breed\ListBreedController
  methods: ['GET']

get_one:
  path: '/breeds/{id}'
  controller: App\Controller\Api\Breed\ListBreedController
  methods: ['GET']

delete:
  path: '/breeds/{id}'
  controller: App\Controller\Api\Breed\DeleteBreedController
  methods: ['DELETE']

post:
  path: '/breeds'
  controller: App\Controller\Api\Breed\CreateBreedController
  methods: ['POST']

patch:
  path: '/breeds/{id}'
  controller: App\Controller\Api\Breed\EditBreedController
  methods: ['PATCH']

get_pets:
  path: '/breeds/{id}/pets'
  controller: App\Controller\Api\Breed\ListPetByBreedControlller
  methods: ['GET']

