get:
  path: '/pet-types'
  controller: App\Controller\Api\PetType\ListPetTypeController
  methods: ['GET']

get_one:
  path: '/pet-types/{id}'
  controller: App\Controller\Api\PetType\ListPetTypeController
  methods: ['GET']

post:
  path: '/pet-types'
  controller: App\Controller\Api\PetType\CreatePetTypeController
  methods: ['POST']

patch:
  path: '/pet-types/{id}'
  controller: App\Controller\Api\PetType\EditPetTypeController
  methods: ['PATCH']