get:
  path: '/pets'
  controller: App\Controller\Api\Pet\ListPetController
  methods: ['GET']

get_one:
  path: '/pets/{id}'
  controller: App\Controller\Api\Pet\ListPetController
  methods: ['GET']

delete:
  path: '/pets/{id}'
  controller: App\Controller\Api\Pet\DeletePetController
  methods: ['DELETE']

patch:
  path: '/pets/{id}'
  controller: App\Controller\Api\Pet\EditPetController
  methods: ['PATCH']
