get:
  path: '/users'
  controller: App\Controller\Api\User\ListUserController
  methods: ['GET']

get_one:
  path: '/users/{id}'
  controller: App\Controller\Api\User\ListUserController
  methods: ['GET']

delete:
  path: '/users/{id}'
  controller: App\Controller\Api\User\DeleteUserController
  methods: ['DELETE']

POST:
  path: '/users'
  controller: App\Controller\Api\User\CreateUserController
  methods: ['POST']
