admin_breed:
  resource: admin/breed.yaml
  name_prefix: admin_breed_

admin_pettype:
  resource: admin/pettype.yaml
  name_prefix: admin_pettype_

admin_pet:
  resource: admin/pet.yaml
  name_prefix: admin_pet_

admin_ngo:
  resource: admin/ngo.yaml
  name_prefix: admin_ngo_