api_breed:
  resource: api/breed.yaml
  name_prefix: api_breed_

api_user:
  resource: api/user.yaml
  name_prefix: api_user_

api_ngo:
  resource: api/ngo.yaml
  name_prefix: api_ngo_

api_pet:
  resource: api/pet.yaml
  name_prefix: api_pet_
