api_breed:
  resource: api/breed.yaml
  name_prefix: api_breed_

api_pet-type:
  resource: api/pet-type.yaml
  name_prefix: api_pet-type_

api_user:
  resource: api/user.yaml
  name_prefix: api_user_

api_ngo:
  resource: api/ngo.yaml
  name_prefix: api_ngo_
